### ISSUE TITLE
Error in reduce_impl, line 277 and 454

### ISSUE THREAD

**Issue by GustawEriksson** [fagostini/R_Gencode_Reference#1]
Hello,

I am getting error messages at line 277:
> exons.pc.granges = reduce(split(temp, temp$gene_id))
Error in reduce_impl(.x, .f, ..., .init = .init, .dir = .dir) : 
  argument ".f" is missing, with no default

and line 454:
> exons = reduce(split(exons, exons$name))
Error in reduce_impl(.x, .f, ..., .init = .init, .dir = .dir) : 
  argument ".f" is missing, with no default

**Comment by fagostini** [comment]
Can you paste the result of `sessionInfo()`?
Thank you
